const $ = (q) => document.querySelector(q);
const $$ = (q) => [...document.querySelectorAll(q)];

const scenarios = {
  credential: { label:'Credential + PowerShell', sub:'Identity → execution', logs:`2026-08-13T09:41:22Z user=j.santos src_ip=185.220.101.44 host=FIN-WS22 action=login_failed detail="Invalid password"
2026-08-13T09:41:36Z user=j.santos src_ip=185.220.101.44 host=FIN-WS22 action=login_failed detail="Invalid password"
2026-08-13T09:42:04Z user=j.santos src_ip=185.220.101.44 host=FIN-WS22 action=login_success detail="MFA approved from new country"
2026-08-13T09:44:18Z user=j.santos src_ip=185.220.101.44 host=FIN-WS22 process=powershell.exe action=process_start command="powershell -enc SQBFAFgA... download cradle"
2026-08-13T09:44:29Z user=j.santos host=FIN-WS22 process=powershell.exe dst=cdn-update-check.com dst_ip=91.215.85.19 action=network_connection
2026-08-13T09:45:02Z user=j.santos host=FIN-WS22 process=rundll32.exe hash=44d88612fea8a8f36de82e1278abb02f action=process_start detail="Unsigned payload"
2026-08-13T09:48:17Z user=j.santos host=FIN-WS22 action=credential_dump detail="LSASS access detected"`},
  ransomware:{label:'Ransomware movement',sub:'Lateral spread → impact',logs:`2026-08-13T02:14:05Z user=svc_backup host=SRV-FILE01 src_ip=10.20.4.18 action=login_success detail="Remote service logon"
2026-08-13T02:15:11Z user=svc_backup host=SRV-FILE01 process=psexec.exe action=process_start command="psexec \\SRV-FILE02 cmd.exe"
2026-08-13T02:16:02Z user=svc_backup host=SRV-FILE02 src_ip=10.20.4.21 action=lateral_movement detail="SMB admin share accessed"
2026-08-13T02:18:33Z user=svc_backup host=SRV-FILE02 process=vssadmin.exe action=process_start command="vssadmin delete shadows /all /quiet"
2026-08-13T02:19:47Z user=svc_backup host=SRV-FILE02 process=encryptor.exe hash=5d41402abc4b2a76b9719d911017c592 action=file_encryption detail="842 files modified"
2026-08-13T02:21:04Z user=svc_backup host=SRV-DC01 action=login_success detail="Privileged remote logon"
2026-08-13T02:22:39Z user=svc_backup host=SRV-DC01 action=ransom_note detail="README_RECOVER.txt created"`},
  admin:{label:'Suspicious admin',sub:'Privilege → persistence',logs:`2026-08-13T23:04:11Z user=a.rahman src_ip=45.142.212.61 host=ADMIN-JUMP action=login_success detail="Out-of-hours login from new ASN"
2026-08-13T23:06:18Z user=a.rahman host=ADMIN-JUMP action=role_change detail="Added self to Domain Admins"
2026-08-13T23:08:31Z user=a.rahman host=SRV-DC01 process=net.exe action=account_create command="net user audit_svc /add"
2026-08-13T23:09:02Z user=a.rahman host=SRV-DC01 action=group_change detail="audit_svc added to Administrators"
2026-08-13T23:11:25Z user=a.rahman host=SRV-DC01 process=schtasks.exe action=persistence command="schtasks /create /tn UpdateCheck"
2026-08-13T23:14:49Z user=a.rahman host=SRV-DC01 dst=drop-sync.net dst_ip=194.26.135.119 action=network_connection detail="Rare destination"`},
  phishing:{label:'Phishing compromise',sub:'Email → command & control',logs:`2026-08-13T11:20:08Z user=m.chen src_ip=203.0.113.45 host=MAIL action=email_received sender=payroll@corp-benefits.co detail="Urgent Payroll Adjustment"
2026-08-13T11:22:17Z user=m.chen host=MKT-LT14 action=url_click dst=corp-benefits.co detail="Credential capture link"
2026-08-13T11:24:03Z user=m.chen src_ip=198.51.100.72 host=MKT-LT14 action=login_success detail="New device login"
2026-08-13T11:27:44Z user=m.chen host=MKT-LT14 process=winword.exe action=process_start detail="Invoice.docm opened"
2026-08-13T11:27:58Z user=m.chen host=MKT-LT14 process=powershell.exe parent=winword.exe action=process_start command="powershell -w hidden -enc JABjAGw..."
2026-08-13T11:28:16Z user=m.chen host=MKT-LT14 process=powershell.exe dst=assets-cloudfront.net dst_ip=103.27.186.12 action=network_connection
2026-08-13T11:31:50Z user=m.chen host=MKT-LT14 action=mailbox_rule detail="Forward all mail externally"`}
};

const techniqueRules = [
  [/login_failed|new country|new device|credential/i,'T1078','Valid Accounts','Initial Access'],[/powershell/i,'T1059.001','PowerShell','Execution'],[/credential_dump|lsass/i,'T1003.001','LSASS Memory','Credential Access'],[/psexec|remote service/i,'T1021.002','SMB/Windows Admin Shares','Lateral Movement'],[/vssadmin|delete shadows/i,'T1490','Inhibit System Recovery','Impact'],[/file_encryption|ransom/i,'T1486','Data Encrypted for Impact','Impact'],[/role_change|group_change|domain admins/i,'T1098','Account Manipulation','Persistence'],[/schtasks|scheduled task/i,'T1053.005','Scheduled Task/Job','Persistence'],[/url_click|email_received|docm/i,'T1566.002','Spearphishing Link','Initial Access'],[/winword.*powershell|parent=winword/i,'T1204.002','Malicious File','Execution'],[/network_connection|rare destination/i,'T1071.001','Web Protocols','Command and Control'],[/mailbox_rule|forward all/i,'T1114.003','Email Forwarding Rule','Collection']
];
const actionInfo={login_failed:['Failed authentication','Repeated authentication failure'],login_success:['Successful authentication','Account access was granted'],process_start:['Process execution','A process was launched'],network_connection:['Outbound connection','A process contacted a destination'],credential_dump:['Credential access','Credential material may have been accessed'],lateral_movement:['Lateral movement','Activity moved to another system'],file_encryption:['Mass file encryption','Files were rapidly modified'],ransom_note:['Ransomware impact','A ransom note was created'],role_change:['Privilege escalation','Administrative privilege was changed'],group_change:['Administrative group change','A privileged membership was changed'],account_create:['New account created','A local or domain account was created'],persistence:['Persistence established','A scheduled task was configured'],email_received:['Suspicious email delivered','A likely lure reached the user'],url_click:['Suspicious link opened','The user followed an untrusted link'],mailbox_rule:['Mailbox rule created','Email forwarding behavior changed']};
let state=null;

function escapeHTML(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function parseKV(line){const out={raw:line};const rx=/(\w+)=((?:"[^"]*")|(?:[^\s,]+))/g;let m;while((m=rx.exec(line)))out[m[1]]=m[2].replace(/^"|"$/g,'');const ts=line.match(/^\d{4}-\d\d-\d\d[T ][\d:.]+Z?/);if(ts)out.timestamp=ts[0];return out}
function parseInput(text){let rows=[];const t=text.trim();if(!t)return rows;try{const j=JSON.parse(t);rows=(Array.isArray(j)?j:(j.events||j.logs||[j])).map(x=>({...x,raw:JSON.stringify(x)}))}catch{const lines=t.split(/\r?\n/).filter(Boolean);if(lines[0]?.includes(',')&&!lines[0].includes('=')){const h=splitCSV(lines[0]);rows=lines.slice(1).map(l=>Object.fromEntries(h.map((k,i)=>[k,splitCSV(l)[i]||''])))}else rows=lines.map(parseKV)}return rows.map((r,i)=>normalize(r,i)).filter(r=>Object.keys(r).length>2)}
function splitCSV(s){return (s.match(/("[^"]*(?:""[^"]*)*"|[^,]+|(?<=,)(?=,))/g)||[]).map(x=>x.replace(/^"|"$/g,'').replace(/""/g,'"').trim())}
function normalize(r,i){const pick=(...ks)=>ks.map(k=>r[k]).find(Boolean);return{...r,id:i+1,timestamp:pick('timestamp','time','date','@timestamp')||new Date(Date.now()+i*1000).toISOString(),user:pick('user','username','account','principal'),host:pick('host','hostname','device','endpoint'),src_ip:pick('src_ip','source_ip','src'),dst_ip:pick('dst_ip','destination_ip'),dst:pick('dst','domain','destination','url'),process:pick('process','process_name','image'),action:pick('action','event_type','event','activity')||'event',detail:pick('detail','message','description','command')||r.raw||'',raw:r.raw||JSON.stringify(r)}}
function uniq(a){return [...new Set(a.filter(Boolean))]}
function analyze(text){const events=parseInput(text).sort((a,b)=>new Date(a.timestamp)-new Date(b.timestamp));if(!events.length){toast('No recognizable events found');return}const corpus=events.map(e=>Object.values(e).join(' ')).join(' ');const ips=uniq([...events.flatMap(e=>[e.src_ip,e.dst_ip]),...(corpus.match(/\b(?:\d{1,3}\.){3}\d{1,3}\b/g)||[])]);const domains=uniq([...events.map(e=>e.dst),...(corpus.match(/\b(?:[a-z0-9-]+\.)+(?:com|net|org|io|co|ru|xyz)\b/gi)||[])]).filter(x=>!/^\d/.test(x));const hashes=uniq(corpus.match(/\b[a-f0-9]{32}\b|\b[a-f0-9]{40}\b|\b[a-f0-9]{64}\b/gi)||[]);const users=uniq(events.map(e=>e.user));const hosts=uniq(events.map(e=>e.host));const processes=uniq(events.map(e=>e.process));const techniques=[];techniqueRules.forEach(([rx,id,name,tactic])=>{const matches=events.filter(e=>rx.test(Object.values(e).join(' ')));if(matches.length)techniques.push({id,name,tactic,count:matches.length,evidence:matches[0].detail||matches[0].action})});let score=18+Math.min(30,events.length*3)+Math.min(28,techniques.length*4);if(/credential_dump|file_encryption|ransom_note|domain admins/i.test(corpus))score+=18;if(/powershell|psexec|schtasks/i.test(corpus))score+=8;score=Math.min(98,score);const severity=score>=80?'CRITICAL':score>=60?'HIGH':score>=40?'MEDIUM':'LOW';const confidence=Math.min(99,55+events.length*3+techniques.length*4);const type=/ransom|file_encryption/i.test(corpus)?'Probable ransomware propagation':/email_received|url_click|docm/i.test(corpus)?'Phishing-led account compromise':/role_change|group_change|schtasks/i.test(corpus)?'Suspicious privileged activity':/credential_dump|powershell/i.test(corpus)?'Credential compromise with malicious execution':'Correlated suspicious activity';const summary=makeSummary(type,events,{users,hosts,ips,domains,processes},techniques);state={events,ips,domains,hashes,users,hosts,processes,techniques,score,severity,confidence,type,...summary};render()}
function makeSummary(type,events,e,t){const first=events[0],last=events.at(-1);let narrative=`${events.length} correlated events involve ${e.users.length||0} user${e.users.length===1?'':'s'} and ${e.hosts.length||0} endpoint${e.hosts.length===1?'':'s'}. `;if(e.processes.length)narrative+=`Observed execution includes ${e.processes.slice(0,3).join(', ')}. `;if(e.domains.length||e.ips.length)narrative+=`Network indicators suggest contact with ${[...e.domains,...e.ips].slice(0,2).join(' and ')}.`;const key=t.length?`${t[0].name} (${t[0].id}) appears in the evidence and chains with ${t.slice(1,3).map(x=>x.name).join(' and ')||'related suspicious activity'}.`:'Multiple related events share users, hosts, and temporal proximity.';const mins=Math.max(0,Math.round((new Date(last.timestamp)-new Date(first.timestamp))/60000));return{narrative,key,mins}}

function render(){const s=state;$('#emptySummary').classList.add('hidden');$('#summaryContent').classList.remove('hidden');$('#results').classList.remove('hidden');$('#caseId').textContent='CASE—'+new Date().toISOString().slice(2,10).replaceAll('-','')+'-'+String(s.events.length).padStart(3,'0');$('#riskScore').textContent=s.score;$('#riskOrb').style.background=`conic-gradient(${s.score>=80?'var(--red)':s.score>=60?'var(--amber)':'var(--cyan)'} 0 ${s.score}%,#1a2b30 ${s.score}%)`;$('#severity').textContent=s.severity;$('#severity').style.color=s.score>=80?'var(--red)':s.score>=60?'var(--amber)':'var(--cyan)';$('#incidentTitle').textContent=s.type;$('#summaryText').textContent=s.narrative;$('#confidence').textContent=s.confidence+'%';$('#eventCount').textContent=s.events.length;$('#entityCount').textContent=s.users.length+s.hosts.length+s.ips.length+s.domains.length+s.hashes.length+s.processes.length;$('#timeSpan').textContent=s.mins<1?'<1m':s.mins+'m';$('#keyFinding').textContent=s.key;renderTimeline();renderIOCs();renderMitre();renderResponse();renderGraph();$('#results').scrollIntoView({behavior:'smooth',block:'start'});toast('Analysis complete · '+s.events.length+' events correlated')}
function renderTimeline(){$('#timelineBadge').textContent=state.events.length;$('#timelineList').innerHTML=state.events.map(e=>{const inf=actionInfo[e.action]||['Observed event','Security telemetry event'];const high=/credential_dump|file_encryption|ransom_note|role_change|persistence/.test(e.action);const tags=uniq([e.user,e.host,e.process,e.src_ip,e.dst,e.dst_ip]).slice(0,5);return`<div class="timeline-item ${high?'high':''}"><time class="timeline-time">${escapeHTML(new Date(e.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}))}</time><div class="timeline-spine"><i></i></div><div class="timeline-body"><strong>${escapeHTML(inf[0])}</strong><p>${escapeHTML(e.detail||inf[1])}</p><div class="event-tags">${tags.map(x=>`<span>${escapeHTML(x)}</span>`).join('')}</div></div></div>`}).join('')}
function renderIOCs(){const groups=[['Users',state.users,'Identity'],['Endpoints',state.hosts,'Asset'],['IP addresses',state.ips,'Network'],['Domains',state.domains,'Network'],['File hashes',state.hashes,'Artifact'],['Processes',state.processes,'Execution']];$('#iocGrid').innerHTML=groups.filter(g=>g[1].length).map(([name,items,type])=>`<div class="ioc-card"><small>${type} · ${items.length}</small><strong>${name}</strong>${items.map(x=>`<span>• ${escapeHTML(x)}</span><br>`).join('')}</div>`).join('')}
function renderMitre(){$('#mitreGrid').innerHTML=state.techniques.length?state.techniques.map(t=>`<div class="mitre-card"><small>${escapeHTML(t.tactic)}</small><strong>${escapeHTML(t.name)}</strong><b>${t.id}</b><p>Matched ${t.count} event${t.count===1?'':'s'} · ${escapeHTML(t.evidence)}</p></div>`).join(''):'<p>No ATT&CK technique rules matched.</p>'}
function recommendations(){const c=state.events.map(e=>Object.values(e).join(' ')).join(' ');const r=[];if(state.hosts.length)r.push(['Isolate affected endpoint'+(state.hosts.length>1?'s':''),`Quarantine ${state.hosts.slice(0,3).join(', ')} while preserving forensic evidence.`,true]);if(state.users.length)r.push(['Secure involved identities',`Disable or reset sessions and credentials for ${state.users.join(', ')}; review MFA methods.`,true]);if(state.ips.length||state.domains.length)r.push(['Block observed indicators',`Block and hunt for ${[...state.ips,...state.domains].slice(0,4).join(', ')} across security controls.`,false]);if(/ransom|file_encryption|vssadmin/i.test(c))r.push(['Protect recovery assets','Segment file servers, validate immutable backups, and stop active encryption.',true]);if(/email|mailbox|url_click/i.test(c))r.push(['Contain phishing exposure','Remove the lure from mailboxes, revoke active sessions, and review forwarding rules.',false]);r.push(['Expand the investigation','Hunt for the same users, hashes, processes, and destinations across the prior 30 days.',false]);return r}
function renderResponse(){$('#responseGrid').innerHTML=recommendations().map((r,i)=>`<div class="response-card ${r[2]?'priority':''}"><small>${r[2]?'Immediate':'Next'} · ${String(i+1).padStart(2,'0')}</small><strong>${escapeHTML(r[0])}</strong><p>${escapeHTML(r[1])}</p></div>`).join('')}
function renderGraph(){const nodes=[];state.users.slice(0,2).forEach(x=>nodes.push({x:100,y:100+nodes.length*120,label:x,type:'u'}));state.hosts.slice(0,3).forEach((x,i)=>nodes.push({x:330,y:70+i*120,label:x,type:'e'}));state.processes.slice(0,3).forEach((x,i)=>nodes.push({x:570,y:70+i*120,label:x,type:'p'}));[...state.domains,...state.ips.filter(x=>!x.startsWith('10.'))].slice(0,3).forEach((x,i)=>nodes.push({x:790,y:70+i*120,label:x,type:'x'}));const colors={u:'#55e6d0',e:'#6fa8ff',p:'#ffbd59',x:'#ff6577'};let edges='';for(let i=1;i<nodes.length;i++){const prev=[...nodes.slice(0,i)].reverse().find(n=>['u','e','p'][['e','p','x'].indexOf(nodes[i].type)]===n.type)||nodes[i-1];edges+=`<line class="edge" x1="${prev.x}" y1="${prev.y}" x2="${nodes[i].x}" y2="${nodes[i].y}"/>`}const ns=nodes.map(n=>`<g class="node"><circle cx="${n.x}" cy="${n.y}" r="25" fill="${colors[n.type]}18" stroke="${colors[n.type]}"/><text x="${n.x}" y="${n.y+43}" text-anchor="middle">${escapeHTML(n.label.slice(0,23))}</text><text x="${n.x}" y="${n.y+3}" text-anchor="middle" fill="${colors[n.type]}">${n.type.toUpperCase()}</text></g>`).join('');$('#attackGraph').innerHTML=edges+ns}

function answer(q){if(!state)return 'I need evidence first. Load a sample scenario or paste logs, then run the analysis.';const s=state,k=q.toLowerCase();if(/what happened|summary|explain/.test(k))return `${s.type}. ${s.narrative} Confidence is ${s.confidence}%.`;if(/asset|host|device|affected/.test(k))return `Affected endpoints: ${s.hosts.join(', ')||'none identified'}. Involved users: ${s.users.join(', ')||'none identified'}.`;if(/contain|first|respond|recommend/.test(k)){const r=recommendations()[0];return `First priority: ${r[0]}. ${r[1]}`};if(/why|suspicious|sever|risk/.test(k))return `Risk is ${s.score}/100 (${s.severity}) because ${s.techniques.length} ATT&CK techniques were matched across ${s.events.length} temporally correlated events. ${s.key}`;if(/mitre|technique|attack/.test(k))return s.techniques.length?`Mapped techniques: ${s.techniques.map(t=>`${t.id} ${t.name}`).join('; ')}.`:'No ATT&CK rules matched this evidence.';if(/ioc|indicator|ip|domain|hash/.test(k))return `Indicators: ${[...s.ips,...s.domains,...s.hashes].join(', ')||'none extracted'}.`;if(/user|account|identity/.test(k))return `Involved identities: ${s.users.join(', ')||'none extracted'}. Review their sessions, MFA events, privilege changes, and activity on other endpoints.`;if(/timeline|when|duration/.test(k))return `The incident contains ${s.events.length} events over ${s.mins<1?'less than one minute':s.mins+' minutes'}, beginning ${new Date(s.events[0].timestamp).toLocaleString()}.`;return `From the available evidence, this is assessed as ${s.severity} severity with ${s.confidence}% confidence. Ask me about the summary, affected assets, indicators, ATT&CK techniques, timeline, or containment.`}
function ask(q){if(!q.trim())return;$('#chat').insertAdjacentHTML('beforeend',`<div class="message user"><span>YOU</span><p>${escapeHTML(q)}</p></div><div class="message bot"><span>AI</span><p>${escapeHTML(answer(q))}</p></div>`);$('#chat').scrollTop=$('#chat').scrollHeight;$('#questionInput').value=''}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function loadScenario(key){const s=scenarios[key];$('#evidenceInput').value=s.logs;updateMeta();$$('.scenario-card').forEach(x=>x.classList.toggle('active',x.dataset.key===key));analyze(s.logs)}
Object.entries(scenarios).forEach(([key,s])=>$('#scenarioList').insertAdjacentHTML('beforeend',`<button class="scenario-card" data-key="${key}"><span>${s.label}</span><small>${s.sub}</small></button>`));
$('#scenarioList').addEventListener('click',e=>{const b=e.target.closest('button');if(b)loadScenario(b.dataset.key)});$('#browseBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>readFile(e.target.files[0]);const dz=$('#dropzone');['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>readFile(e.dataTransfer.files[0]));function readFile(f){if(!f)return;if(f.size>5e6){toast('File exceeds 5 MB');return}const r=new FileReader();r.onload=()=>{$('#evidenceInput').value=r.result;updateMeta();toast(`${f.name} loaded`)};r.readAsText(f)}
function updateMeta(){const v=$('#evidenceInput').value;$('#lineCount').textContent=(v? v.split(/\r?\n/).length:0)+' lines';$('#formatHint').textContent='Format: '+(!v?'auto-detect':v.trim().startsWith('{')||v.trim().startsWith('[')?'JSON':v.split('\n')[0]?.includes(',')&&!v.split('\n')[0]?.includes('=')?'CSV':'raw log')}
$('#evidenceInput').addEventListener('input',updateMeta);$('#analyzeBtn').onclick=()=>analyze($('#evidenceInput').value);$('#tabs').onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab-panel').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab))};$('#askForm').onsubmit=e=>{e.preventDefault();ask($('#questionInput').value)};$('#suggestions').onclick=e=>{if(e.target.tagName==='BUTTON')ask(e.target.textContent)};$('#themeBtn').onclick=()=>document.body.classList.toggle('light');$('#exportBtn').onclick=()=>{if(!state)return;const report={generatedAt:new Date().toISOString(),incident:{title:state.type,severity:state.severity,risk:state.score,confidence:state.confidence,summary:state.narrative,keyFinding:state.key},entities:{users:state.users,hosts:state.hosts,ips:state.ips,domains:state.domains,hashes:state.hashes,processes:state.processes},techniques:state.techniques,recommendations:recommendations().map(x=>({title:x[0],detail:x[1],immediate:x[2]})),timeline:state.events};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));a.download='sentinel-forge-report.json';a.click();URL.revokeObjectURL(a.href)};
setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('en-GB'),1000);$('#clock').textContent=new Date().toLocaleTimeString('en-GB');
